<?php require "inc/screen.php" ?>
<?php require "inc/about.php" ?>
<?php require "inc/services.php" ?>
<?php require "inc/infoblock.php" ?>
<?php require "inc/map.php" ?>
<?php require "inc/app.php" ?>
<?php require "inc/process.php" ?>
<?php require "inc/token.php" ?>
<?php require "inc/docs.php" ?>
<?php require "inc/faq.php" ?>
<?php require "inc/team.php" ?>
<?php require "inc/partners.php" ?>